Revert "Start enforcing scheduler throughput to be 90+ in density test"
Error: scheduler throughput: actual throughput 23 lower than threshold 90
This reverts commit f73bf4dc59c29b746a1d47aba1d96f0a07cfa4ff.